[package]
name = "chicken_tui_client"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
log = "0.4.25"
chicken_core = { path = "../chicken_core" }
ratatui = "0.29.0"
crossterm = "0.28.1"
