[package]
name = "mailbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
json = "0.12.4"
serde_json = "1.0.108"
sqlite = "0.32.0"
